server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Service Worker must NOT be cached
    location /service-worker.js {
        add_header Cache-Control "no-cache";
    }

    # Manifest also should not be cached aggressively
    location /manifest.json {
        add_header Cache-Control "no-cache";
    }

    # Cache assets
    location ~* \.(js|css|png|jpg|jpeg|svg|ico)$ {
        expires 7d;
        add_header Cache-Control "public";
    }
}